// bench/tasks/code-locate.mjs
//
// CATEGORY: code-locate  (SURVIVABLE)
//
// Each task dumps one or several large SOURCE FILES as junk — either re-pasted
// 3-5 times byte-identical (collapsed by dedup) or delivered as OLD role:'tool'
// read_file results (older ones elided, keepRecent=1). The question asks to
// LOCATE something verifiable about the code: the line a function is defined on,
// the value of a constant, which file imports a module, the name of an exported
// symbol, etc.
//
// HONESTY CONTRACT for this category:
//   * The answerable detail ALWAYS lives in a RECENT message (a final
//     user/assistant turn) OR in the single retained copy of a deduplicated
//     block. The junk that gets compacted away (older tool dumps, earlier
//     duplicate copies) is genuinely irrelevant to the question — it is the same
//     code re-pasted, or unrelated files — so eliding/deduping it cannot change
//     the answer.
//   * A correct compactor keeps the signal (the recent statement, or the kept
//     dedup copy) => the GOVERNED answer matches BASELINE while using far fewer
//     tokens.
//
// Graders are objective: exact line numbers (number-extract), exact constant
// values, exact filenames / symbol names (toLowerCase().includes). Empty and
// wrong answers are rejected.
//
// Plain Node ESM, dependency-free, no network, no imports.

// ---------------------------------------------------------------------------
// Source-file fixtures. These are realistic-looking code blobs. We line-number
// them deterministically so the "what line is X on?" answers are exact and
// stable. We also re-paste / dump them at scale to clear the >=5000-token
// (~20000+ char) bloat floor per task.
// ---------------------------------------------------------------------------

/**
 * Render an array of source lines with a leading "NNN: " 1-based gutter so the
 * question "on what line is X defined?" has a single deterministic answer that
 * is also visible in the dumped text. The gutter makes the fixture read like a
 * real editor / `cat -n` dump.
 */
function withLineNumbers(lines) {
  return lines
    .map((l, i) => String(i + 1).padStart(3, ' ') + ': ' + l)
    .join('\n');
}

/** Repeat a unit string until the result is at least `minChars` characters. */
function inflate(unit, minChars) {
  let out = '';
  let i = 0;
  while (out.length < minChars) {
    out += unit.replace(/__SEQ__/g, String(i));
    i++;
  }
  return out;
}

/** A big block of UNRELATED source/log filler (no needle). Deterministic. */
function filler(minChars, tag = 'fil') {
  return inflate(
    [
      `// ${tag} __SEQ__ — autogenerated shim, do not edit`,
      'function handler__SEQ__(req, res) {',
      '  const ctx = buildContext(req);',
      '  const t0 = Date.now();',
      '  try {',
      '    const out = dispatch(ctx, req.body);',
      '    res.status(200).json(out);',
      '  } catch (err) {',
      '    logger.error("handler__SEQ__ failed", { err });',
      '    res.status(500).json({ error: "internal" });',
      '  } finally {',
      '    metrics.observe("handler__SEQ__", Date.now() - t0);',
      '  }',
      '}',
      '',
    ].join('\n') + '\n',
    minChars,
  );
}

/** Valid OpenAI tool-call + matching tool result, large content. */
function toolPair(callId, fnName, args, resultText) {
  return [
    {
      role: 'assistant',
      content: null,
      tool_calls: [
        { id: callId, type: 'function', function: { name: fnName, arguments: JSON.stringify(args) } },
      ],
    },
    { role: 'tool', tool_call_id: callId, content: resultText },
  ];
}

// --- Concrete fixture: a small "auth" module whose lines we pin exactly. ----
// Line numbers below are 1-based as rendered by withLineNumbers().
//  1: header comment
//  ...
// The function `computeBackoff` is defined on line 14 (see assertion in note).
const AUTH_MODULE_LINES = [
  '// src/auth/session.js — session + retry helpers',
  "import crypto from 'node:crypto';",
  "import { CONFIG } from '../config/constants.js';",
  '',
  'const TOKEN_BYTES = 24;',
  'const SESSION_TTL_SECONDS = 3600;',
  '',
  'export function newToken() {',
  "  return crypto.randomBytes(TOKEN_BYTES).toString('hex');",
  '}',
  '',
  'export function isExpired(issuedAt, now = Date.now()) {',
  '  return now - issuedAt > SESSION_TTL_SECONDS * 1000;',
  '}',
  'export function computeBackoff(attempt) {',
  '  const base = 200;',
  '  const capped = Math.min(attempt, 6);',
  '  return base * Math.pow(2, capped);',
  '}',
  '',
  'export function rotate(session) {',
  '  session.token = newToken();',
  '  session.issuedAt = Date.now();',
  '  return session;',
  '}',
];
// NOTE: 'export function computeBackoff' is index 14 (0-based) => line 15.
const AUTH_MODULE = withLineNumbers(AUTH_MODULE_LINES);

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

const tasks = [
  // -------------------------------------------------------------------------
  // 1. Line number of a function definition. Junk via OLD read_file tool dumps;
  //    the authoritative line-numbered file is RE-PASTED in the final user turn.
  // -------------------------------------------------------------------------
  {
    id: 'cl-func-line',
    category: 'code-locate',
    answerLocation: 'recent',
    build() {
      const oldDump = '// src/auth/session.js (earlier read)\n' + AUTH_MODULE + '\n\n' + filler(7000, 'noise-a');
      const messages = [
        {
          role: 'system',
          content:
            'You are a code-navigation assistant. When asked for a line number, answer with the exact integer ' +
            'shown in the line-number gutter of the file as provided in the conversation.',
        },
        { role: 'user', content: 'Open src/auth/session.js and a couple of the handler shims so we can review the retry logic.' },
        ...toolPair('call_1', 'read_file', { path: 'src/auth/session.js' }, oldDump),
        ...toolPair('call_2', 'read_file', { path: 'src/handlers/a.js' }, filler(8000, 'handlers-a')),
        ...toolPair('call_3', 'read_file', { path: 'src/handlers/b.js' }, filler(8000, 'handlers-b')),
        { role: 'assistant', content: 'Reviewed session.js and the handler shims. Ready for your question.' },
        // RECENT authoritative copy: the exact line-numbered file, pasted fresh.
        {
          role: 'user',
          content:
            'Here is the current src/auth/session.js with line numbers, freshly re-read:\n\n' +
            AUTH_MODULE +
            '\n\nOn what line is the function computeBackoff defined?',
        },
      ];
      return { messages, question: 'On what line number is the function computeBackoff defined in src/auth/session.js?' };
    },
    expected: '15',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const nums = (answer.match(/\d+/g) || []).map(Number);
      return nums.includes(15);
    },
    note: 'The line-numbered file is re-pasted in the final user turn (kept); old read_file dumps and handler shims are irrelevant junk that elision/dedup remove without touching the answer.',
  },

  // -------------------------------------------------------------------------
  // 2. Value of a named constant. Junk via DEDUP (same big file pasted 3x);
  //    the kept copy still contains the constant.
  // -------------------------------------------------------------------------
  {
    id: 'cl-const-value',
    category: 'code-locate',
    answerLocation: 'duplicated',
    build() {
      const constsLines = [
        '// src/config/constants.js — global tuning knobs',
        'export const CONFIG = {',
        '  RETRY_LIMIT: 5,',
        '  CACHE_TTL_SECONDS: 300,',
        '  MAX_UPLOAD_BYTES: 10485760,',
        '  MAX_BATCH_SIZE: 8192,',
        '  REQUEST_TIMEOUT_MS: 5000,',
        '};',
        '',
      ];
      // Make one substantial, byte-identical block (>200 chars) by padding with
      // unrelated-but-identical filler so the three pastes dedup cleanly.
      const block =
        '===== src/config/constants.js (full) =====\n' +
        withLineNumbers(constsLines) +
        '\n' +
        filler(8000, 'consts-pad') +
        '\n===== end constants.js =====';
      const messages = [
        { role: 'system', content: 'You are a code-navigation assistant. Report exact constant values as written in the source.' },
        { role: 'user', content: 'Reference file (constants), paste 1 of 3 so it stays in view:\n' + block },
        { role: 'assistant', content: 'Got copy 1 of constants.js.' },
        { role: 'user', content: 'Same file again, paste 2 of 3 (identical):\n' + block },
        { role: 'assistant', content: 'Copy 2 matches copy 1 byte-for-byte.' },
        { role: 'user', content: 'And paste 3 of 3, identical, just in case it scrolled off:\n' + block },
        { role: 'assistant', content: 'Confirmed — all three copies of constants.js are identical.' },
        { role: 'user', content: 'What integer is MAX_BATCH_SIZE set to in CONFIG?' },
      ];
      return { messages, question: 'What integer value is CONFIG.MAX_BATCH_SIZE set to in src/config/constants.js?' };
    },
    expected: '8192',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const nums = answer.match(/\d{3,8}/g) || [];
      return nums.includes('8192');
    },
    note: 'MAX_BATCH_SIZE=8192 lives inside the thrice-pasted identical file; dedup keeps exactly one copy that still contains it, so the answer survives.',
  },

  // -------------------------------------------------------------------------
  // 3. Which file imports a given module. Junk via OLD grep-style tool dumps;
  //    the authoritative answer is stated in a RECENT assistant message.
  // -------------------------------------------------------------------------
  {
    id: 'cl-which-file-imports',
    category: 'code-locate',
    answerLocation: 'recent',
    build() {
      const messages = [
        {
          role: 'system',
          content: 'You are a code-navigation assistant. When asked which file imports a module, answer with the exact file path.',
        },
        { role: 'user', content: 'Search the repo for everything that imports the rate-limiter package so we can audit usage.' },
        // OLD large tool results: noisy ripgrep dumps full of unrelated matches.
        ...toolPair('call_1', 'ripgrep', { pattern: "from '.*'" }, '// ripgrep full dump (imports across repo)\n' + filler(8000, 'rg-a')),
        ...toolPair('call_2', 'ripgrep', { pattern: 'require(' }, '// ripgrep full dump (require across repo)\n' + filler(8000, 'rg-b')),
        ...toolPair('call_3', 'read_file', { path: 'package.json' }, '// package.json + lockfile excerpt\n' + filler(8000, 'pkg')),
        { role: 'user', content: 'So, narrowing down: which single source file actually imports the express-rate-limit module?' },
        // RECENT authoritative answer in the assistant turn.
        {
          role: 'assistant',
          content:
            "I traced the imports. Exactly one source file imports express-rate-limit: src/middleware/throttle.js " +
            "(line: import rateLimit from 'express-rate-limit'). No other file references it.",
        },
        { role: 'user', content: 'Confirm the file path that imports express-rate-limit.' },
      ];
      return { messages, question: 'Which source file imports the express-rate-limit module?' };
    },
    expected: 'src/middleware/throttle.js',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const a = answer.toLowerCase().replace(/\\/g, '/');
      return a.includes('src/middleware/throttle.js');
    },
    note: 'The file path is stated in the recent assistant turn; the old ripgrep/package dumps are unrelated bulk matches that elision removes without affecting the answer.',
  },

  // -------------------------------------------------------------------------
  // 4. Name of the exported default symbol. Junk via OLD read_file dump of the
  //    whole module; the authoritative line-numbered file is RE-PASTED recently.
  // -------------------------------------------------------------------------
  {
    id: 'cl-default-export-name',
    category: 'code-locate',
    answerLocation: 'recent',
    build() {
      const moduleLines = [
        '// src/services/billing/InvoiceReconciler.js',
        "import { Decimal } from '../../lib/decimal.js';",
        "import { ledgerFor } from '../ledger.js';",
        '',
        'class InvoiceReconciler {',
        '  constructor(tenantId) {',
        '    this.tenantId = tenantId;',
        '    this.ledger = ledgerFor(tenantId);',
        '  }',
        '',
        '  reconcile(invoices) {',
        '    let residual = new Decimal(0);',
        '    for (const inv of invoices) residual = residual.plus(inv.delta);',
        '    return residual.toFixed(4);',
        '  }',
        '}',
        '',
        'export default InvoiceReconciler;',
      ];
      const fileText = withLineNumbers(moduleLines);
      const oldDump = '// earlier read of the billing service\n' + fileText + '\n\n' + filler(7000, 'billing-noise');
      const messages = [
        {
          role: 'system',
          content: 'You are a code-navigation assistant. When asked for an exported symbol name, answer with the exact identifier.',
        },
        { role: 'user', content: 'Open the billing reconciler module and a few of its sibling shims.' },
        ...toolPair('call_1', 'read_file', { path: 'src/services/billing/InvoiceReconciler.js' }, oldDump),
        ...toolPair('call_2', 'read_file', { path: 'src/services/billing/helpers.js' }, filler(12000, 'billing-helpers')),
        { role: 'assistant', content: 'Loaded the reconciler and helper shims.' },
        // RECENT authoritative copy of the file, re-pasted with line numbers.
        {
          role: 'user',
          content:
            'Here is src/services/billing/InvoiceReconciler.js as it stands now:\n\n' +
            fileText +
            '\n\nWhat is the name of the class that this file exports as its default export?',
        },
      ];
      return { messages, question: 'What identifier does src/services/billing/InvoiceReconciler.js export as its default export?' };
    },
    expected: 'InvoiceReconciler',
    grade(answer) {
      return typeof answer === 'string' && answer.toLowerCase().includes('invoicereconciler');
    },
    note: 'The default export name appears in the freshly re-pasted file (kept) and the question; the old read_file dump + helper shim are irrelevant junk that compaction removes.',
  },

  // -------------------------------------------------------------------------
  // 5. Line number of a specific TODO marker. Junk via DEDUP (same file 4x).
  //    The needle line is inside the kept dedup copy.
  // -------------------------------------------------------------------------
  {
    id: 'cl-todo-line',
    category: 'code-locate',
    answerLocation: 'duplicated',
    build() {
      const lines = [
        '// src/pipeline/runner.js',
        "import { stages } from './stages/index.js';",
        '',
        'export async function run(ctx, payload) {',
        '  let acc = payload;',
        '  for (const stage of stages) {',
        '    acc = await stage(ctx, acc);',
        '  }',
        '  // TODO(ENG-4471): add per-stage timeout + cancellation here',
        '  return acc;',
        '}',
      ];
      // The TODO is index 8 (0-based) => line 9.
      const fileText = withLineNumbers(lines);
      const block =
        '===== src/pipeline/runner.js (full, line-numbered) =====\n' +
        fileText +
        '\n' +
        filler(5500, 'runner-pad') +
        '\n===== end runner.js =====';
      const messages = [
        { role: 'system', content: 'You are a code-navigation assistant. Report the exact line number from the gutter shown.' },
        { role: 'user', content: 'Pipeline runner, copy 1 of 4 (keep for reference):\n' + block },
        { role: 'assistant', content: 'Received runner.js copy 1.' },
        { role: 'user', content: 'Runner again, copy 2 of 4 (identical):\n' + block },
        { role: 'assistant', content: 'Copy 2 matches copy 1.' },
        { role: 'user', content: 'Runner copy 3 of 4 (identical):\n' + block },
        { role: 'assistant', content: 'Copy 3 identical.' },
        { role: 'user', content: 'Runner copy 4 of 4 (identical), final paste:\n' + block },
        { role: 'assistant', content: 'All four copies of runner.js are byte-for-byte identical.' },
        { role: 'user', content: 'On what line is the TODO comment referencing ENG-4471?' },
      ];
      return { messages, question: 'On what line number is the TODO comment referencing ENG-4471 in src/pipeline/runner.js?' };
    },
    expected: '9',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const nums = (answer.match(/\d+/g) || []).map(Number);
      return nums.includes(9);
    },
    note: 'The line-numbered TODO is inside the four-times-pasted identical file; dedup keeps one copy that still shows line 9, so the answer survives.',
  },

  // -------------------------------------------------------------------------
  // 6. Value of an enum / status code mapping. Junk via OLD tool dumps; the
  //    authoritative mapping is stated in a RECENT assistant message.
  // -------------------------------------------------------------------------
  {
    id: 'cl-enum-value',
    category: 'code-locate',
    answerLocation: 'recent',
    build() {
      const messages = [
        {
          role: 'system',
          content: 'You are a code-navigation assistant. Report exact numeric values as defined in the source.',
        },
        { role: 'user', content: 'Dump the status-code enum file and the surrounding error modules so we can audit codes.' },
        ...toolPair('call_1', 'read_file', { path: 'src/errors/codes.js' }, '// codes.js earlier read (verbose)\n' + filler(8000, 'codes-a')),
        ...toolPair('call_2', 'read_file', { path: 'src/errors/messages.js' }, filler(8000, 'messages')),
        ...toolPair('call_3', 'read_file', { path: 'src/errors/legacy.js' }, filler(8000, 'legacy')),
        { role: 'user', content: 'In the current enum, what numeric code is RATE_LIMITED mapped to?' },
        // RECENT authoritative answer.
        {
          role: 'assistant',
          content:
            'In src/errors/codes.js the enum maps RATE_LIMITED to the numeric code 42901 ' +
            '(it is the only entry in the 429xx band; TIMEOUT is 50400 and CONFLICT is 40901).',
        },
        { role: 'user', content: 'Repeat just the numeric code for RATE_LIMITED.' },
      ];
      return { messages, question: 'What numeric code is RATE_LIMITED mapped to in src/errors/codes.js?' };
    },
    expected: '42901',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const nums = answer.match(/\d{4,6}/g) || [];
      return nums.includes('42901');
    },
    note: 'The RATE_LIMITED=42901 mapping is stated in the recent assistant turn; the three old read_file dumps are unrelated verbose source that elision removes without changing the answer.',
  },

  // -------------------------------------------------------------------------
  // 7. Which file DEFINES a given symbol (path). Junk via OLD symbol-search tool
  //    dumps + DEDUP of an unrelated big file; the answer is in a PINNED message.
  // -------------------------------------------------------------------------
  {
    id: 'cl-defines-symbol',
    category: 'code-locate',
    answerLocation: 'pinned',
    build() {
      const dupNoise = '===== unrelated vendored bundle (identical paste) =====\n' + filler(6000, 'vendor') + '\n===== end =====';
      const messages = [
        {
          role: 'system',
          content: 'You are a code-navigation assistant. When asked where a symbol is defined, answer with the exact file path.',
        },
        { role: 'user', content: 'Find where the helper function parseDurationToMs is defined across the codebase.' },
        ...toolPair('call_1', 'symbol_search', { name: 'parseDurationToMs' }, '// symbol search raw output (noisy)\n' + filler(8000, 'sym-a')),
        // PINNED authoritative answer — kept verbatim wherever it sits.
        {
          role: 'user',
          content:
            '<!--ctxgov:pin--> AUTHORITATIVE: the function parseDurationToMs is defined exactly once, in ' +
            'src/utils/time.js. Every other occurrence is just an import of it.',
        },
        ...toolPair('call_2', 'symbol_search', { name: 'parseDurationToMs' }, '// second noisy symbol search\n' + filler(8000, 'sym-b')),
        { role: 'user', content: 'Reference vendored bundle, identical paste 1 of 2:\n' + dupNoise },
        { role: 'assistant', content: 'Got bundle copy 1.' },
        { role: 'user', content: 'Identical paste 2 of 2:\n' + dupNoise },
        { role: 'assistant', content: 'Copy 2 matches copy 1; reviewed.' },
        { role: 'user', content: 'Which file defines parseDurationToMs?' },
      ];
      return { messages, question: 'In which source file is the function parseDurationToMs defined?' };
    },
    expected: 'src/utils/time.js',
    grade(answer) {
      if (typeof answer !== 'string') return false;
      const a = answer.toLowerCase().replace(/\\/g, '/');
      return a.includes('src/utils/time.js');
    },
    note: 'The defining file path is in a pin-sentinel message (kept verbatim); the noisy symbol-search tool dumps and the twice-pasted vendored bundle are irrelevant junk removed by elision/dedup.',
  },
];

export default tasks;
