// bench/tasks/dedup.mjs
//
// CATEGORY: dedup (SURVIVABLE)
//
// Each task simulates an agent that re-pastes the SAME large file/log block
// 3-5 times across the conversation (byte-identical, each >200 chars, total
// well over 5000 tokens / 20000 chars of junk). The question is answerable
// from ONE copy of the block, and the answerable needle lives INSIDE the
// duplicated block itself. Because every copy is identical, deduplication
// collapses the duplicates down to a single retained copy that STILL contains
// the needle -> the governed answer survives.
//
// Honesty note: the needle is inside the (identical) duplicated content, not
// hidden in unrelated elided junk. A correct compactor keeps exactly one copy,
// which is sufficient to answer. Nothing relevant is thrown away.

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// Repeat a unit string until the result is at least `minChars` characters.
function inflate(unit, minChars) {
  let out = '';
  let i = 0;
  while (out.length < minChars) {
    out += unit.replace(/__SEQ__/g, String(i));
    i++;
  }
  return out;
}

// A realistic-looking application log block. The needle (an error code) is
// embedded once near the middle. Total length is padded well past 200 chars
// many times over so a single copy is already a substantial block.
function buildAppLog(needleLine) {
  const noise = inflate(
    [
      '2026-03-11T08:14:0__SEQ__Z INFO  [http] GET /api/v1/orders 200 12ms trace=ab__SEQ__cd',
      '2026-03-11T08:14:0__SEQ__Z INFO  [cache] hit key=user:__SEQ__ ttl=300s region=eu-west-1',
      '2026-03-11T08:14:0__SEQ__Z DEBUG [pool] acquire conn=__SEQ__ idle=4 active=11 max=32',
      '2026-03-11T08:14:0__SEQ__Z INFO  [auth] token refreshed sub=svc-__SEQ__ exp=3600',
      '2026-03-11T08:14:0__SEQ__Z WARN  [rate] soft-limit nearing client=__SEQ__ used=88%',
      '2026-03-11T08:14:0__SEQ__Z DEBUG [sql] SELECT id,name FROM accounts WHERE shard=__SEQ__',
    ].join('\n') + '\n',
    4200,
  );
  const tail = inflate(
    [
      '2026-03-11T08:15:1__SEQ__Z INFO  [worker] job done id=__SEQ__ took=42ms queue=default',
      '2026-03-11T08:15:1__SEQ__Z DEBUG [gc] young collection freed=__SEQ__MB pause=2ms',
      '2026-03-11T08:15:1__SEQ__Z INFO  [http] POST /api/v1/checkout 201 88ms trace=ef__SEQ__01',
    ].join('\n') + '\n',
    2600,
  );
  return (
    '===== service.log (payments-gateway, prod) =====\n' +
    noise +
    needleLine +
    '\n' +
    tail +
    '===== end service.log =====\n'
  );
}

// A realistic config file dump. The needle is a specific config value.
function buildConfig(needleAssignment) {
  const front = inflate(
    [
      '# autogenerated config block __SEQ__ — do not edit by hand',
      'http.keepalive_seconds = __SEQ__0',
      'http.max_connections = 2048',
      'logging.level = info',
      'logging.format = json',
      'metrics.enabled = true',
      'metrics.flush_interval_ms = __SEQ__00',
      'cache.backend = redis',
      'cache.ttl_seconds = 300',
      'db.pool.min = 4',
      'db.pool.max = 32',
    ].join('\n') + '\n',
    2800,
  );
  const back = inflate(
    [
      'feature.flag.experimental___SEQ__ = false',
      'tracing.sample_rate = 0.1',
      'tls.min_version = 1.2',
      'queue.prefetch = __SEQ__6',
    ].join('\n') + '\n',
    1700,
  );
  return (
    '##### /etc/payments/gateway.conf #####\n' +
    front +
    needleAssignment +
    '\n' +
    back +
    '##### EOF gateway.conf #####\n'
  );
}

// A realistic source file. The needle is a function defined on a known line.
function buildSource(needleFunctionLine) {
  // We want the needle to land on a predictable line number, so build a header
  // with a fixed number of lines, then the needle, then filler.
  const headerLines = [
    '// module: billing/retry.ts',
    '// owner: payments-platform',
    "import { sleep } from '../util/time';",
    "import { logger } from '../util/log';",
    '',
    'const BASE_DELAY_MS = 250;',
    'const JITTER_MS = 50;',
    '',
    'export interface RetryOptions {',
    '  attempts: number;',
    '  factor: number;',
  ];
  // needle goes on line 12 (1-indexed)
  const filler = inflate(
    [
      '  // detail __SEQ__: backoff is multiplicative with full jitter applied',
      '  // detail __SEQ__: callers must pass an idempotency key for safety',
      '  // detail __SEQ__: transient 5xx and 429 are retried, 4xx are not',
      '  // detail __SEQ__: max total wall-clock is capped at 30 seconds',
    ].join('\n') + '\n',
    7400,
  );
  return (
    headerLines.join('\n') +
    '\n' +
    needleFunctionLine +
    '\n' +
    filler +
    '// end of billing/retry.ts\n'
  );
}

// A realistic JSON-ish API response dump. The needle is a specific id/value.
function buildJsonDump(needleField) {
  const rows = inflate(
    '  { "id": __SEQ__, "status": "ok", "latency_ms": 12, "region": "eu-west-1", "node": "n-__SEQ__" },\n',
    5400,
  );
  return (
    '----- captured response: GET /admin/diagnostics -----\n' +
    '{\n' +
    '  "service": "payments-gateway",\n' +
    '  "version": "4.7.2",\n' +
    '  ' + needleField + ',\n' +
    '  "nodes": [\n' +
    rows +
    '    { "id": 9999, "status": "ok", "latency_ms": 9, "region": "eu-west-1", "node": "n-tail" }\n' +
    '  ]\n' +
    '}\n' +
    '----- end capture -----\n'
  );
}

// A realistic stack-trace / incident paste. The needle is the build hash.
function buildStackTrace(needleBuildLine) {
  const frames = inflate(
    [
      '    at PaymentRouter.dispatch (router.js:__SEQ__:18)',
      '    at async Pipeline.run (pipeline.js:__SEQ__:7)',
      '    at async Worker.handle (worker.js:__SEQ__:33)',
      '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
    ].join('\n') + '\n',
    4600,
  );
  return (
    '########## INCIDENT-2026-0311 stack capture ##########\n' +
    needleBuildLine +
    '\n' +
    'Error: upstream connect timeout after 5000ms\n' +
    frames +
    '########## end stack capture ##########\n'
  );
}

// Wrap a big identical block into a duplicated-paste conversation.
// `blockLabel` is what the agent "says" when re-pasting (slightly varied
// wrapper text — but the BLOCK itself is byte-identical every time).
function dupConversation(block, copies) {
  const messages = [
    {
      role: 'system',
      content:
        'You are a senior SRE assistant helping triage a production incident. ' +
        'You read pasted logs, configs, and source files and answer precisely. ' +
        'Always answer with the exact value requested and nothing speculative.',
    },
  ];
  const wrappers = [
    'Here is the file again so you have it in context:',
    'Pasting the same artifact once more for reference:',
    'Re-attaching the artifact (unchanged) below:',
    'One more copy of the artifact, just to be safe:',
    'Including the artifact yet again so nothing is lost:',
  ];
  for (let i = 0; i < copies; i++) {
    messages.push({
      role: 'user',
      content: wrappers[i % wrappers.length] + '\n\n' + block,
    });
    messages.push({
      role: 'assistant',
      content:
        'Got it — I have the artifact loaded (copy ' +
        (i + 1) +
        '). Standing by for your question.',
    });
  }
  return messages;
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

const tasks = [
  // 1) Error code in a duplicated log block ---------------------------------
  {
    id: 'dedup-log-errcode',
    category: 'dedup',
    answerLocation: 'duplicated',
    build() {
      const block = buildAppLog(
        '2026-03-11T08:14:59Z ERROR [payments] charge declined gateway=stripe error_code=ZX-7782 retryable=false',
      );
      const messages = dupConversation(block, 4);
      const question =
        'In the pasted service.log, the payments charge was declined. ' +
        'What is the exact error_code on that ERROR line?';
      messages.push({ role: 'user', content: question });
      return { messages, question };
    },
    expected: 'ZX-7782',
    grade(answer) {
      return String(answer || '').toLowerCase().includes('zx-7782');
    },
    note: 'Needle (error_code=ZX-7782) lives inside the identical block re-pasted 4x; dedup keeps one copy which still contains it.',
  },

  // 2) MAX_RETRIES value in a duplicated config -----------------------------
  {
    id: 'dedup-config-maxretries',
    category: 'dedup',
    answerLocation: 'duplicated',
    build() {
      const block = buildConfig('retry.MAX_RETRIES = 13');
      const messages = dupConversation(block, 5);
      const question =
        'In the pasted gateway.conf, what is the value of retry.MAX_RETRIES? ' +
        'Answer with just the number.';
      messages.push({ role: 'user', content: question });
      return { messages, question };
    },
    expected: '13',
    grade(answer) {
      const m = String(answer || '').match(/\b(\d{1,4})\b/);
      return m ? Number(m[1]) === 13 : false;
    },
    note: 'Needle (retry.MAX_RETRIES = 13) is inside the byte-identical config pasted 5x; surviving deduped copy still answers it.',
  },

  // 3) Function defined on line 12 of a duplicated source file --------------
  {
    id: 'dedup-source-line12',
    category: 'dedup',
    answerLocation: 'duplicated',
    build() {
      // Header is exactly 11 lines (indices 0..10), so this is line 12.
      const block = buildSource(
        'export function computeBackoffWindow(attempt: number): number {',
      );
      const messages = dupConversation(block, 3);
      const question =
        'In the pasted billing/retry.ts source file, what is the name of the ' +
        'function defined on line 12? Answer with just the function name.';
      messages.push({ role: 'user', content: question });
      return { messages, question };
    },
    expected: 'computeBackoffWindow',
    grade(answer) {
      return String(answer || '')
        .toLowerCase()
        .includes('computebackoffwindow');
    },
    note: 'Header is fixed 11 lines so the needle function sits on line 12 inside the identical source pasted 3x; dedup retains one copy.',
  },

  // 4) Specific field value in a duplicated JSON diagnostics dump -----------
  {
    id: 'dedup-json-incidentid',
    category: 'dedup',
    answerLocation: 'duplicated',
    build() {
      const block = buildJsonDump('"active_incident_id": "INC-44821"');
      const messages = dupConversation(block, 4);
      const question =
        'In the pasted /admin/diagnostics JSON response, what is the value of ' +
        'the "active_incident_id" field? Give the exact id.';
      messages.push({ role: 'user', content: question });
      return { messages, question };
    },
    expected: 'INC-44821',
    grade(answer) {
      return String(answer || '').toLowerCase().includes('inc-44821');
    },
    note: 'Needle ("active_incident_id":"INC-44821") is inside the identical JSON dump pasted 4x; the deduped surviving copy still contains it.',
  },

  // 5) Build hash on the top line of a duplicated stack trace ---------------
  {
    id: 'dedup-stack-buildhash',
    category: 'dedup',
    answerLocation: 'duplicated',
    build() {
      const block = buildStackTrace(
        'service=payments-gateway version=4.7.2 build=9f3ac1e2 commit=deadbeef',
      );
      const messages = dupConversation(block, 5);
      const question =
        'In the pasted INCIDENT-2026-0311 stack capture, what is the build ' +
        'hash (the value after build=)? Answer with just the hash.';
      messages.push({ role: 'user', content: question });
      return { messages, question };
    },
    expected: '9f3ac1e2',
    grade(answer) {
      return String(answer || '').toLowerCase().includes('9f3ac1e2');
    },
    note: 'Needle (build=9f3ac1e2) lives in the identical stack-trace header pasted 5x; dedup collapses to one copy that still has the hash.',
  },
];

export default tasks;
